In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from dt_apriltags import Detector
import matplotlib.cm as cm
from lane_detection import *
from lane_following import *

In [ ]:
IMAGE_FILE = "lanes-15b8289a06a1b1e8a17347ad29bb1988.png"
# IMAGE_FILE = "rov_pool.jpg"

In [ ]:
img = cv2.imread(IMAGE_FILE)
#img = cv2.imread("rov_pool.jpg")

In [ ]:
lines = lane_detection.detect_lines(img, 49, 50, 3, 500, 40)
print(lines)

In [ ]:
lane_detection.draw_lines(img, lines)

In [ ]:
lane_detection.get_slopes_intercepts(lines)

In [ ]:
lanes = lane_detection.detect_lanes(lines)
print(lanes)


In [ ]:
image = cv2.imread(IMAGE_FILE)

In [ ]:
lane_detection.draw_lanes(image, lanes)
plt.imshow(cv2.cvtColor(lane_detection.draw_lanes(image, lanes), cv2.COLOR_BGR2RGB))
plt.show()

In [ ]:
#new_image = lane_detection.literallyEverything(img, 50, 90, 3, 10)

In [ ]:
#plt.imshow(cv2.cvtColor(lane_detection.literallyEverything(cv2.imread(IMAGE_FILE)), cv2.COLOR_BGR2RGB))

In [ ]:
#lane_detection.draw_lines(img, lines)

In [3]:
video = cv2.VideoCapture('AUV_Vid.mkv')

fps = int(video.get(cv2.CAP_PROP_FPS))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))

output_file = 'output_video.avi'4
fourcc = cv2.VideoWriter_fourcc(*'XVID')
output_video = cv2.VideoWriter(output_file, fourcc, 30, (width, height))

ret = True
while ret:
    slopeSet = set() 
    ret, frame = video.read()
    lines = detect_lines(frame, 50, 90, 3,150,10)
    print (lines)

    try:
        lanes = detect_lanes(lines)
        pickedLane = pick_lane(lanes)
        frame = draw_Single_lane(frame, pickedLane, (255, 0, 0))
        frame = draw_lines(frame, lines,(0, 255, 0))
        center_intercept, center_slope = get_lane_center(pickedLane)
        xPoint = pickedLane[0][2]
        yPoint = pickedLane[0][3]
        cv2.line(frame, (int(center_intercept), 1080), (int(xPoint), int(yPoint)), (0,0,255), 3)

        output_video.write(frame)
    except:
        pass
        
        
    recommend_direction(center_intercept, center_slope)
    #plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    #plt.show()

video.release()
output_video.release()

[[[1365  789 1544  865]]

 [[1687  925 1891 1011]]

 [[1725  887 1898  950]]

 [[1288  757 1704  933]]

 [[ 843  849  959 1077]]

 [[1621  848 1803  914]]]
strafe right
turn right
[[[1384  797 1745  950]]

 [[1541  819 1883  944]]

 [[1641  905 1841  990]]

 [[ 843  848  959 1077]]

 [[ 855  870  961 1078]]

 [[1739  946 1918 1022]]]
strafe right
turn right
[[[1595  886 1839  989]]

 [[1373  793 1621  898]]

 [[1532  815 1804  914]]

 [[1619  848 1886  945]]

 [[ 838  837  959 1075]]

 [[1714  935 1910 1018]]]
strafe right
turn right
[[[1618  847 1897  948]]

 [[1687  924 1866 1000]]

 [[1393  801 1734  945]]

 [[ 878  917  960 1079]]]
strafe right
turn right
[[[1308  764 1714  936]]

 [[1531  814 1807  915]]

 [[1624  897 1812  977]]

 [[ 839  838  961 1078]]

 [[ 842  847  947 1052]]]
strafe right
turn right
[[[1543  818 1897  947]]

 [[1354  783 1724  940]]

 [[ 816  793  960 1076]]

 [[1710  932 1866  998]]

 [[ 825  812  933 1024]]]
strafe right
turn right
[[[1566  825 1901  947]]

/home/josh/cv-intro/lane_detection.py:71: RuntimeWarning: divide by zero encountered in scalar divide
  slope = (y2-y1)/(x2-x1)
/home/josh/cv-intro/lane_detection.py:95: RuntimeWarning: invalid value encountered in scalar divide
  xPoint = ((slopeList[i] * xInterceptList[i]) - (slopeList[j] * xInterceptList[j]))/(slopeList[i]-slopeList[j])


[[[939 675 996 862]]

 [[786 999 789 834]]

 [[887 509 970 779]]]
strafe right
turn Left
[[[ 781 1079  784  901]]

 [[ 887  502  966  759]]

 [[ 934  651 1005  884]]]
strafe right
turn Left
[[[ 869  434 1064 1073]]]
strafe right
turn Left
[[[ 916  585 1022  931]]

 [[ 938  654  987  813]]

 [[ 986  816 1064 1072]]

 [[ 863  411  934  641]]]
strafe right
turn right
[[[ 916  578 1036  972]]

 [[ 864  406  923  596]]

 [[ 988  819 1067 1078]]]
strafe right
turn right
[[[ 893  494  977  771]]

 [[ 972  761 1020  918]]

 [[1639  476 1919  572]]

 [[ 945  667 1038  973]]

 [[ 762 1077  770  923]]

 [[1009  883 1068 1076]]]
strafe right
turn Left
[[[1593  452 1911  561]]

 [[ 946  668 1024  923]]

 [[ 918  573  973  753]]]
strafe right
turn right
[[[ 893  476  983  787]]

 [[1720  489 1885  543]]

 [[ 943  647 1017  905]]

 [[ 873  411  941  647]]]
strafe right
turn right
[[[ 881  427 1011  881]]

 [[ 764  860  774  707]]

 [[1731  485 1919  546]]

 [[ 967  725 1030  944]]]
strafe right
turn 

/home/josh/cv-intro/lane_detection.py:95: RuntimeWarning: divide by zero encountered in scalar divide
  xPoint = ((slopeList[i] * xInterceptList[i]) - (slopeList[j] * xInterceptList[j]))/(slopeList[i]-slopeList[j])


[[[ 770  642  792  455]]

 [[ 954  635 1010  847]]

 [[ 729  977  754  771]]

 [[ 974  802 1029 1042]]

 [[ 960  804 1013 1078]]

 [[ 949  863  983 1077]]

 [[ 981  804 1038 1052]]

 [[ 925  857  952 1078]]

 [[ 919  858  946 1079]]

 [[ 962  846 1003 1057]]

 [[ 877  343  942  588]]

 [[ 902  919  916 1079]]

 [[ 902  849  922 1079]]

 [[ 942  860  976 1076]]]
strafe right
turn Left
[[[ 749  784  770  632]]

 [[ 919  498  992  773]]

 [[ 899  835  920 1079]]

 [[ 975  807 1036 1072]]

 [[ 957  787 1006 1041]]

 [[ 971  759 1034 1036]]

 [[ 917  854  944 1071]]

 [[ 941  863  975 1077]]

 [[ 969  693 1018  875]]

 [[ 953  896  980 1071]]

 [[ 872  858  883 1079]]

 [[ 849  854  852 1053]]

 [[ 925  862  951 1070]]

 [[ 963  849  995 1016]]]
strafe right
turn Left
[[[ 784  524  807  363]]

 [[ 899  409  972  699]]

 [[ 771  612  798  418]]

 [[1003  820 1053 1021]]

 [[ 730  913  752  757]]

 [[ 705 1064  729  897]]

 [[ 965  866  997 1035]]

 [[ 908  790  941 1066]]

 [[ 989  833 1041 

/home/josh/cv-intro/lane_detection.py:95: RuntimeWarning: invalid value encountered in scalar subtract
  xPoint = ((slopeList[i] * xInterceptList[i]) - (slopeList[j] * xInterceptList[j]))/(slopeList[i]-slopeList[j])


[[[ 843 1077 1015  629]]

 [[1114  530 1199  933]]

 [[1113  852 1125 1079]]

 [[1115  777 1130 1056]]

 [[1136  855 1159 1076]]

 [[1091 1019 1091  772]]

 [[ 962 1079 1013  819]]

 [[1059 1077 1070  862]]

 [[ 857 1042  931  849]]

 [[1011 1009 1045  774]]

 [[1165  852 1200 1079]]

 [[1162  760 1205  966]]

 [[1098 1079 1098  880]]

 [[1025 1079 1050  838]]

 [[ 874 1079  960  829]]

 [[ 895 1000  947  841]]

 [[ 930 1079  979  880]]

 [[1065 1073 1077  830]]

 [[1149  800 1194 1079]]

 [[1140  840 1165 1079]]

 [[1180  839 1215 1003]]

 [[1032 1077 1055  858]]

 [[ 912 1033  957  877]]]
strafe left
turn right
[[[1114  540 1200  945]]

 [[ 839 1079 1025  593]]

 [[ 965 1079 1020  800]]

 [[ 871 1079  943  868]]

 [[ 959 1079 1009  824]]

 [[1090 1075 1090  856]]

 [[1120  883 1130 1077]]

 [[1010  998 1042  774]]

 [[1135  859 1158 1076]]

 [[1096 1033 1096  859]]

 [[1112  861 1124 1079]]

 [[1141  859 1164 1077]]

 [[ 993 1073 1017  903]]

 [[1034  988 1054  762]]

 [[1163  852 11

/home/josh/cv-intro/lane_detection.py:73: RuntimeWarning: divide by zero encountered in scalar divide
  intercept = ((((2160 - y1)/slope)  )+ x1)


[[[ 165  968  385  776]]

 [[ 552  917  654  688]]

 [[1394  438 1707  438]]

 [[ 212  926  380  780]]]
strafe left
turn Left
[[[ 173  944  347  798]]

 [[ 571  850  649  684]]

 [[ 535  926  643  694]]

 [[ 507  983  615  753]]

 [[  64 1037  217  908]]]
strafe left
turn Left
[[[ 123  976  310  819]]

 [[ 501  972  639  689]]

 [[ 116  980  392  749]]

 [[ 485 1001  580  806]]]
strafe left
turn Left
[[[  74 1008  368  762]]

 [[ 194  909  376  756]]

 [[ 519  912  627  700]]

 [[  12 1055  182  917]]

 [[ 475  678  629  535]]]
strafe left
turn Left
[[[   0 1064  284  834]]

 [[  14 1050  181  915]]

 [[ 210  891  370  761]]

 [[ 426 1079  515  911]]

 [[ 497  942  625  700]]

 [[ 541  856  628  692]]]
strafe left
turn Left
[[[   8 1056  171  924]]

 [[ 171  923  350  778]]

 [[  64 1012  277  839]]

 [[ 419 1076  556  820]]

 [[ 518  895  607  727]]

 [[ 444  964  537  809]]]
strafe left
turn Left
[[[   5 1064  269  851]]

 [[ 518  890  612  720]]

 [[   1 1066  324  804]]

 [[   1 10

/home/josh/cv-intro/lane_detection.py:93: RuntimeWarning: invalid value encountered in scalar subtract
  if(abs(xInterceptList[i]-xInterceptList[j])< 10000 and abs(1/ slopeList[i]-1 /slopeList[j]) < 1):


[[[1428  973 1647 1019]]

 [[ 856  923 1016  975]]

 [[1067  990 1223 1040]]

 [[1707  661 1877  661]]

 [[1040  888 1206  924]]

 [[1637 1019 1901 1079]]]
strafe right
turn right
[[[1169  925 1669 1031]]

 [[1402  973 1561 1006]]

 [[ 898  946 1137 1023]]

 [[1635  663 1815  660]]

 [[1074 1002 1285 1070]]

 [[1050  898 1270  945]]]
strafe right
turn right
[[[1336  967 1561 1015]]

 [[1377  975 1555 1012]]

 [[1219  943 1385  978]]

 [[1394  668 1544  665]]

 [[1028  998 1270 1076]]

 [[ 787  921 1024  998]]]
strafe right
turn right
[[[1279  962 1476 1003]]

 [[1171  940 1337  975]]

 [[1477 1003 1694 1049]]

 [[1023 1006 1242 1077]]

 [[ 911  972 1089 1029]]]
strafe right
turn right
[[[1611  666 1792  663]]

 [[1272  967 1494 1014]]

 [[ 996  910 1228  959]]

 [[1092  930 1315  977]]

 [[1053 1028 1215 1078]]

 [[ 834  959  985 1006]]]
strafe right
turn right
[[[1046  928 1229  966]]

 [[ 806  962 1104 1053]]

 [[1235  969 1421 1005]]

 [[1462 1013 1669 1054]]

 [[1424  671 1604  668

error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
